<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>
<?php
    $Contact_Information = $block->getLayout()->createBlock('Nvspromo\ZohoOrderHistory\Block\Open\OrderHistory');
    $Contact_Name = '';
    $Contact_Email = '';
    $Billing_Name = '';
    $Street = '';
    $State = '';
    $City = '';
    $Zip = '';
    $Country = '';
    $phone = '';
    foreach ($Contact_Information->getContactDetails() as $key => $value) {
      $Contact_Name = $value['Full_Name'];
      $Contact_Email = $value['Email'];
      $Billing_Name = $value['Billing_Name'];
      $Street = $value['Mailing_Street'];
      $City = $value['Mailing_City'];
      $Zip = $value['Mailing_Zip'];
      $Country = $value['Mailing_Country'];
      $phone = $value['Phone'];
      $State = $value['Mailing_State'];
    }
?>
<div class="block block-dashboard-info">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Contact Details')) ?></strong></div>
    <div class="block-content">
        <div class="box box-information">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Contact Information')) ?></span>
            </strong>
            <div class="box-content">
                <p>
                    <?= $block->escapeHtml($Contact_Name) ?><br>
                    <?= $block->escapeHtml($Contact_Email) ?><br>
                    <?= $block->escapeHtml('Phone Number : '.$phone) ?><br>
                </p>
                <?= $block->getChildHtml('customer.account.dashboard.info.extra'); ?>
            </div>
            <!-- <div class="box-actions">
                <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('customer/account/edit')) ?>">
                    <span><?= $block->escapeHtml(__('Edit')) ?></span>
                </a>
                <a href="<?= $block->escapeUrl($block->getChangePasswordUrl()) ?>" class="action change-password">
                    <?= $block->escapeHtml(__('Change Password')) ?>
                </a>
            </div> -->
        </div>
        <div class="box box-information">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Address Information')) ?></span>
            </strong>
            <div class="box-content">
                <p>
                    <?= $block->escapeHtml($Billing_Name) ?><br>
                    <?= $block->escapeHtml($Street) ?><br>
                    <?= $block->escapeHtml($City) ?>
                    <?= $block->escapeHtml($State) ?>
                    <?= $block->escapeHtml($Zip) ?><br>
                    <?= $block->escapeHtml($Country) ?>
                </p>
                <?= $block->getChildHtml('customer.account.dashboard.info.extra'); ?>
            </div>
        </div>
        <!-- <?php if ($block->isNewsletterEnabled()): ?>
            <div class="box box-newsletter">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Newsletters')) ?></span>
                </strong>
                <div class="box-content">
                    <p>
                        <?php if ($block->getIsSubscribed()): ?>
                            <?= $block->escapeHtml(__('You are subscribed to "General Subscription".')) ?>
                        <?php else: ?>
                            <?= $block->escapeHtml(__('You aren\'t subscribed to our newsletter.')) ?>
                        <?php endif; ?>
                    </p>
                </div>
                <div class="box-actions">
                    <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('newsletter/manage')) ?>">
                        <span><?= $block->escapeHtml(__('Edit')) ?></span></a>
                </div>
            </div>
        <?php endif; ?> -->
        <?= $block->getChildHtml('additional_blocks'); ?>
    </div>
</div>
