<?php
 /**
 *
 * @author        Viha Digital Commerce Team <naeem@vdcstore.com>.
 * @copyright     Copyright(c) 2020 Viha Digital Commerce
 * @link          https://www.vihadigitalcommerce.com/
 * @date          28/12/2021
 */
?>
<div class="payorder_success col-lg-6 col-md-6" style="margin: 3% 0 0 35%;">	
	<div class="success_image">
		<img src="<?php echo $this->getMediaUrl().'/nvspromo/Smiley-1.png'; ?>">
	</div>
	<div class="payorder_details">
		<h3>Thank You !</h3>
		<p>Your Order # is <?php echo $this->getOrderid(); ?></p>
		
	</div>
</div>
<style type="text/css">
	.page-title-wrapper{
		display: none;
	}
</style>